### ISSUE TITLE
Access through proxy or load balancer

### ISSUE THREAD

**Issue by realtrynna** [p0vidl0/nestjs-real-ip#11]
Hello, Thank you for creating an impressive library!

Is it possible to identify the IP correctly even when the client accesses through a proxy or load balancer?

```javascript
const ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
```

**Comment by p0vidl0** [comment]
Sure, the underlying library code uses almost all possible IP address sources: headers, context, connection and socket.
Feel free to inspect this [code](https://github.com/supercharge/request-ip/blob/main/src/request.ts).

Closing this issue. Please, feel free to reopen or file a new one if you have a question.

**Comment by p0vidl0** [comment]
Sure, the underlying library code uses almost all possible IP address sources: headers, context, connection and socket.
Feel free to inspect this [code](https://github.com/supercharge/request-ip/blob/main/src/request.ts).

Closing this issue. Please, feel free to reopen or file a new one if you have a question.

**Comment by realtrynna** [comment]
I'll look at the code. Have a nice day
