### ISSUE TITLE
request-ip as peerDependencies

### ISSUE THREAD

**Issue by service-paradis** [p0vidl0/nestjs-real-ip#3]
Hello,

It looks like the dependency to request IPs have been changed from `request-ip` to `@supercharge/request-ip`. Unfortunately, the old one is still requested in `peerDependencies`.

Ref: https://github.com/p0vidl0/nestjs-real-ip/blob/eff99b411fa5c6bef2672c7989a9e1a299b0e879/package.json#L58

**Comment by p0vidl0** [comment]
Fixed. Thank you for the issue,
