### ISSUE TITLE
peer dependencies support v10 of NestJS

### ISSUE THREAD

**Issue by fatlirmorina** [p0vidl0/nestjs-real-ip#8]
As far as we know v10 has just released however this is now causing errors for the package to be added.

Could you update peer dependencies of the package? would of been appreciated.

Note that they no longer support typescript below 4.8
https://docs.nestjs.com/migration-guide#cli-plugins-and-typescript--48

**Comment by p0vidl0** [comment]
Thanks for the report. Will do ASAP.

**Comment by p0vidl0** [comment]
Fixed in v3.0.1.
