### ISSUE TITLE
Some client are providing IPv6 address

### ISSUE THREAD

**Issue by minyoung-jun** [p0vidl0/nestjs-real-ip#9]
Hello!
I found that some client are providing IPv6 address and some client are IPv4.
How could I get IPv4 only?
Thank you!

**Comment by p0vidl0** [comment]
Hi @minyoung-jun!
If a client uses IPv6, it is not possible to obtain their IPv4 address directly. The only viable option would be to configure your server to exclusively listen for IPv4 connections, but this may not be suitable for all situations and is not a recommended approach in the general case.
